### ISSUE TITLE
Update CIViC loader for multi-variant Molecular Profiles

### ISSUE THREAD

**Issue by cgrisdale** [bcgsc/pori_graphkb_loader#110]
CIViC will be making a data schema change that will allow combinations of variants as Molecular Profiles (MPs). MPs will be linked to EIDs as opposed to a single gene and variant.
MPs can have combinations of variants linked by AND/OR/NOT.

Example of single gene-variant EID: https://civicdb.org/evidence/2135/summary
Example of multi-variant MP (data from EID2135 and EID2506 combined): https://staging.civicdb.org/evidence/10635/summary

Relevant part of API return with current schema:
![image](https://user-images.githubusercontent.com/3093548/194613923-e0b8b039-8d36-4d6d-bd0b-5d1696f9e845.png)

Relevant part of API return with new schema using MPs:
![image](https://user-images.githubusercontent.com/3093548/194612812-c80c6d93-e712-4580-995b-c9a54b430cf0.png)

**Comment by cgrisdale** [comment]
CIViC v2.2.0 with Molecular Profiles has been rolled out.

The following are the breaking changes that were part of this release:

- Evidence Items and Assertions are no longer attached to Variants. They are attached to the new Molecular Profile concept.
- The Clinical Significance Field has been renamed to Significance.
- Drugs are now referred to as Therapies, and Drug Interaction Type is now Therapy Interaction Type. As a result, Evidence Items and Assertions are linked to Therapies instead of Drugs.
- Variant Description, Sources, and Evidence Score have been moved from Variants to Molecular Profiles

**Comment by mathieulemieux** [comment]
Most of these changes has been addressed in https://github.com/bcgsc/pori_graphkb_loader/pull/112 and https://github.com/bcgsc/pori_graphkb_loader/pull/114.

Complex Molecular Profiles will be soon addressed for expressions with more than 1 variant combined with AND/OR operators. Expression containing the NOT operator are not yet supported; this will require changes to the GraphKB schema.

**Comment by mathieulemieux** [comment]
Complex Molecular Profiles will be soon addressed in https://github.com/bcgsc/pori_graphkb_loader/pull/118. Closing ticket.
