### ISSUE TITLE
Add tests for GraphKB Module Helper Methods

### ISSUE THREAD

**Issue by creisle** [bcgsc/pori_graphkb_loader#39]
Add tests for some of the helper methods in the graphkb loader module

- [simplifyRecordsLinks](https://github.com/bcgsc/pori_graphkb_loader/blob/develop/src/graphkb.js#L29) 
   - [ ] simplifies nested objects into their RID only
- [shouldUpdate](https://github.com/bcgsc/pori_graphkb_loader/blob/develop/src/graphkb.js#L58)
    - [ ] ignores changes in excluded fields
    - [ ] test for disease object
    - [ ] test for statement object
    - [ ] does not return true on a change to a linked/nested field
 - [orderPreferredOntologyTerms](https://github.com/bcgsc/pori_graphkb_loader/blob/develop/src/graphkb.js#L134)
     - [ ] prefers newer version of the same record (sourceIdVersion)
     - [ ] prefer non-deprecated field
     - [ ] prefer specific sources
     - [ ] prefer main non-alias terms
     - [ ] prefer generic rather than version specific terms

Notes & Details:
- test file should follow the convention of the other test files
    - `test/graphkb.test.js` 
- tests are written in [Jest](https://jestjs.io/) and should be run using node (not ts-node)

**Comment by mathieulemieux** [comment]
Hello @creisle !
Is test/graphkb.test.js refering to a particular file?

**Comment by creisle** [comment]
That's is the suggestion for what to name the new file that you put your tests into. In general the tests are name `<module being teste>.test.js`

**Comment by mathieulemieux** [comment]
I commited a test for shouldUpdate(). For orderPreferredOntologyTerms(), I find out that a test already exist here:

**Comment by mathieulemieux** [comment]
I commited a test for shouldUpdate. For orderPreferredOntologyTerms, I find out a test already exist here: https://github.com/bcgsc/pori_graphkb_loader/blob/develop/test/util.test.js#L10. Should I still write a new test for it?
