### ISSUE TITLE
Support new CIViC Evidence Item type

### ISSUE THREAD

**Issue by creisle** [bcgsc/pori_graphkb_loader#5]
CIViC has split the biological evidence items into 2 groups: biological and oncogenic. Will require changes to the CIViC loader to interpret this new class of evidence items

currently these result in errors like this

```
2021-07-05T23:48:28.028Z error: Spec Validation failed for 9151 #.evidence_type should be equal to one of the allowed values found '["Oncogenic"]'
```

**Comment by mathieulemieux** [comment]
All matching between GraphKB Statement's relevances and Civic Evidence Items' type, significance and direction has been addressed in https://github.com/bcgsc/pori_graphkb_loader/pull/112 after discussion in [KBDEV-1015](https://www.bcgsc.ca/jira/browse/KBDEV-1015).
