### ISSUE TITLE
Load CIViC evidence with clinical significance of Unaltered Function

### ISSUE THREAD

**Issue by cgrisdale** [bcgsc/pori_graphkb_loader#59]
Currently we load Functional evidence from CIViC with clinical significance terms: Gain of Function, Loss of Function, Dominant Negative, and Neomorphic. 
There are also Functional evidence items that fall under Unaltered Function. Loading this evidence could be helpful in clarifying the effect of variants in genes/domains where the expectation would be that they have gain or loss of function.

To complete this you will need to
- [x] check that it exists, or add "Unaltered function" to the vocab.json file, 
  - [x] Should be an alias of the term "no functional effect"
- [x] reload the vocab.json file (automatic when this repo is released)

**Comment by creisle** [comment]
To complete this you will need to
- [ ] check that it exists, or add "Unaltered function" to the vocab.json file, make sure to connect to rest of functional-related terms appropriately
- [ ] reload the vocab.json file (automatic when this repo is released)
