### ISSUE TITLE
Update CIViC loader to v2 API

### ISSUE THREAD

**Issue by creisle** [bcgsc/pori_graphkb_loader#88]
## Description

Documentation for v2: https://griffithlab.github.io/civic-v2/

v2 is GraphQL and will be a significant update to the loader

The new GQL endpoint is here: https://civicdb.org/api/graphql

The idea will be that we will still be loading evidence items as statements in GraphKB but now that this is a graph model the elements that are connected to an evidence item may have a different prevelence per evidence item

Here is the documentation specifically for the evidence item query endpoint

https://griffithlab.github.io/civic-v2/#query-evidenceItems

Interactive GraphQL test interface here: https://civicdb.org/api/graphiql

example query to get evidence items provided by civic devs

```graphql
{
  evidenceItems {
    totalCount
    pageInfo {
      endCursor
      hasNextPage
    }
    nodes {
      id
      status
      variant {
        name
        id
        
      }
      gene {
        name
        id
      }
      evidenceType
      evidenceLevel
      evidenceRating
      evidenceDirection
      phenotypes {
        id
        hpoId
      }
      description
      disease {
        id
        doid
        name
      }
      drugs {
        id
        ncitId
        name
      }
      drugInteractionType
    }
  }
}
```

## Tasks
- [x] #92
- [x] #93

**Comment by creisle** [comment]
Once we figure out how to paginate this should be most of what we need for the actual query

```graphql
{
  evidenceItems {
    totalCount
    pageInfo {
      endCursor
      hasNextPage
    }
    nodes {
      id
      status
      variant {
        name
        id
        gene {
          entrezId
          name
        }
      }
      gene {
        name
        id
        entrezId
      }
      evidenceType
      evidenceLevel
      evidenceRating
      evidenceDirection
      status
      flagged
      source {
        citationId
        name
        sourceType
      }
      description
      disease {
        id
        doid
        name
      }
      drugs {
        id
        ncitId
        name
      }
      drugInteractionType
    }
  }
}
```

The structure of the returned record has obviously changed and a number of things have been renamed so those are the things we'll have to change, otherwise this shouldn't be as hard as i'd expected actually

**Comment by creisle** [comment]
I was testing the query in #92  with a diff python-based project that uses a similar method and ran into an error that I think will affect us here. I've made a v2 ticket for it https://github.com/griffithlab/civic-v2/issues/480

**Comment by creisle** [comment]
Other than the variable names and the fetch via qraphQL the only other change we need to account for will be that a couple of fields including the clinical significance are now enums instead of text like values. Things like "Sensitivity/Response" are now "SENSITIVITYRESPONSE"

**Comment by mathieulemieux** [comment]
Issue fixed with PR https://github.com/bcgsc/pori_graphkb_loader/pull/97
